<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="16" passed="12">
  <reporter-output>
    <line>
      <![CDATA[Method name is e2]]>
    </line>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="41" started-at="2020-12-08T23:22:11Z" finished-at="2020-12-08T23:22:11Z">
    <groups>
      <group name="myGroup">
        <method signature="TestClass1.t1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t1" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass1.t2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t2" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass1.t3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t3" class="com.javacodegeeks.testng.reports.TestClass1"/>
        <method signature="TestClass3.d1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass3@15f2bb7]" name="d1" class="com.javacodegeeks.testng.reports.TestClass3"/>
      </group> <!-- myGroup -->
    </groups>
    <test name="Surefire test" duration-ms="41" started-at="2020-12-08T23:22:11Z" finished-at="2020-12-08T23:22:11Z">
      <class name="com.javacodegeeks.testng.reports.TestClass3">
        <test-method status="PASS" signature="d1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass3@15f2bb7]" name="d1" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d1 -->
        <test-method status="PASS" signature="d2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass3@15f2bb7]" name="d2" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- d2 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass3 -->
      <class name="com.javacodegeeks.testng.reports.TestClass4">
        <test-method status="PASS" signature="e1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass4@13c0b17]" name="e1" duration-ms="1" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- e1 -->
        <test-method status="PASS" signature="e2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass4@13c0b17]" name="e2" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
            <line>
              <![CDATA[Method name is e2]]>
            </line>
          </reporter-output>
        </test-method> <!-- e2 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass4 -->
      <class name="com.javacodegeeks.testng.reports.TestClass1">
        <test-method status="FAIL" signature="t1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t1" duration-ms="3" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass1.t1(TestClass1.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method status="FAIL" signature="t2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t2" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass1.t2(TestClass1.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
        <test-method status="PASS" signature="t4()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t4" duration-ms="1" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method status="PASS" signature="t3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t3" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t3 -->
        <test-method status="PASS" signature="t5(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t5" duration-ms="0" started-at="2020-12-08T18:22:11Z" data-provider="dp" finished-at="2020-12-08T18:22:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[two]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
        <test-method status="PASS" signature="t5(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass1@6c658]" name="t5" duration-ms="0" started-at="2020-12-08T18:22:11Z" data-provider="dp" finished-at="2020-12-08T18:22:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[one]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t5 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass1 -->
      <class name="com.javacodegeeks.testng.reports.TestClass2">
        <test-method status="PASS" signature="c2()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@1d4e2ba]" name="c2" duration-ms="1" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c2 -->
        <test-method status="PASS" signature="c1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@1d4e2ba]" name="c1" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c1 -->
        <test-method status="FAIL" signature="c4()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@1d4e2ba]" name="c4" duration-ms="1" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.javacodegeeks.testng.reports.TestClass2.c4(TestClass2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c4 -->
        <test-method status="PASS" signature="c3()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass2@1d4e2ba]" name="c3" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- c3 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass2 -->
      <class name="com.javacodegeeks.testng.reports.TestClass">
        <test-method status="PASS" signature="a1()[pri:0, instance:com.javacodegeeks.testng.reports.TestClass@1a52fbd]" name="a1" duration-ms="7" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a1 -->
        <test-method status="FAIL" signature="a2(java.lang.String)[pri:0, instance:com.javacodegeeks.testng.reports.TestClass@1a52fbd]" name="a2" duration-ms="0" started-at="2020-12-08T18:22:11Z" finished-at="2020-12-08T18:22:11Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'param' is required by @Test on method a2 but has not been marked @Optional or defined
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'param' is required by @Test on method a2 but has not been marked @Optional or defined

	at org.testng.internal.Parameters.createParameters(Parameters.java:155)
	at org.testng.internal.Parameters.createParameters(Parameters.java:358)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:450)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a2 -->
      </class> <!-- com.javacodegeeks.testng.reports.TestClass -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
